version: "3.8"

services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"  # Map container's port 5000 to host's port 5000
    environment:
      - FLASK_APP=app.py  # Set the Flask app file
    command: python -m flask run --host=0.0.0.0 --port=5000
